<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cara a Cara</title>
    <style>
        /* Adicionando CSS diretamente aqui para facilitar */
        body {
            font-family: Arial, sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            margin: 0;
            padding: 20px;
            background-color: #f0f0f0;
        }
        #board {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 10px;
            margin-top: 20px;
        }
        .card {
            width: 100px;
            height: 150px;
            background-color: white;
            border: 2px solid #ccc;
            border-radius: 8px;
            text-align: center;
            padding: 10px;
            cursor: pointer;
            transition: transform 0.2s;
        }
        .card img {
            width: 80px;
            height: 80px;
        }
        .card:hover {
            transform: scale(1.05);
        }
        #question {
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <h1>Jogo Cara a Cara</h1>
    <p>Tente adivinhar o personagem do seu oponente!</p>
    <div id="board">
        <!-- As cartas serão geradas aqui -->
    </div>
    <div id="question">
        <button onclick="askQuestion()">Fazer uma pergunta</button>
    </div>

    <script>
        // Lista de personagens
        const characters = [
            { name: 'Ana', img: 'ana.png', features: { glasses: true, hat: false, beard: false } },
            { name: 'Bruno', img: 'bruno.png', features: { glasses: false, hat: true, beard: true } },
            // Adicione mais personagens conforme necessário
        ];

        // Função para gerar o tabuleiro
        function generateBoard() {
            const board = document.getElementById('board');
            characters.forEach(character => {
                const card = document.createElement('div');
                card.className = 'card';
                card.innerHTML = `
                    <img src="${character.img}" alt="${character.name}">
                    <p>${character.name}</p>
                `;
                board.appendChild(card);
            });
        }

        // Função para fazer uma pergunta (aqui você pode expandir a lógica)
        function askQuestion() {
            alert("Pergunte algo ao seu oponente sobre as características dos personagens!");
        }

        // Inicializar o tabuleiro
        window.onload = generateBoard;
    </script>
</body>
</html>
